apiVersion: v2
name: horizon
description: A CICD DevOps Platform

type: application

version: 2.0.2
appVersion: v2.0.1

dependencies:
  - name: gitlab
    version: 2.0.1
    repository: https://horizoncd.github.io/helm-charts
    condition: gitlab.enabled
  - name: minio
    version: 11.10.13
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: mysql
    version: 9.4.1
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: chartmuseum
    version: 3.9.1
    repository: https://chartmuseum.github.io/charts
    condition: chartmuseum.enabled
  - name: grafana
    version: 6.26.5
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: argo-cd
    version: 5.0.0
    repository: https://argoproj.github.io/argo-helm
    condition: argo-cd.enabled
  - name: harbor
    version: 1.6.3
    repository: https://helm.goharbor.io
    condition: harbor.enabled
