apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
